apiVersion: apps/v1
kind: Deployment
metadata:
  name: cypress-deployment
  labels:
    app: cypress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cypress
  template:
    metadata:
      labels:
        app: cypress
    spec:
      containers:
      - name: cyservice
        image: cyser/cyser
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 8080